### ISSUE TITLE
Discussion: Migrating to Capacitor

### ISSUE THREAD

**Issue by ChunkyProgrammer** [MarmadileManteater/FreeTubeCordova#101]
**Topic**
- [x] Cordova

**Discussion**
I haven't done too much research but it seems like Capacitor is a popular alternative to Cordova that has backwards compatibility support for Cordova plugins and seems to have a more active plugin community. So, I created this discussion to discuss whether it'd be worth it to migrate and to help determine the amount of effort that would go into the migration.

https://capacitorjs.com/docs/cordova#differences-between-capacitor-and-cordova

Migration guide:
https://capacitorjs.com/docs/cordova/migration-strategy
https://capacitorjs.com/docs/cordova/migrating-from-cordova-to-capacitor

Some plugins:
Music controls: https://github.com/ingageco/capacitor-music-controls-plugin-v3

https://github.com/riderx/awesome-capacitor

**Comment by kubo6472** [comment]
I found this project today and I wondered why it chose Cordova instead of Capacitor.

**Comment by MarmadileManteater** [comment]
> I found this project today and I wondered why it chose Cordova instead of Capacitor.

There is no reason. I wasn't aware of capacitor's existence when I started this fork. Now, that I am aware of it, I do admit that it would provide a better workflow, but the reason I haven't just moved forward with migrating to capacitor is because *A.* I haven't had a lot of time to dedicate to FreeTube lately and *B.* I'm worried about spending time migrating to capacitor just to turn around and migrate to Tauri when 2.0 is officially released. I already have a desktop FreeTubeTauri POC which I haven't really told anyone about because I didn't want to stretch myself thin between two forks of the same project. All in all, I have no idea when Tauri 2.0 will be officially released, so maybe, I should just take a weekend and migrate to capacitor for the time being. IDK🤷‍♀️. I've been thinking about it.

**Comment by kubo6472** [comment]
> > I found this project today and I wondered why it chose Cordova instead of Capacitor.
> 
> There is no reason. I wasn't aware of capacitor's existence when I started this fork. Now, that I am aware of it, I do admit that it would provide a better workflow, but the reason I haven't just moved forward with migrating to capacitor is because _A._ I haven't had a lot of time to dedicate to FreeTube lately and _B._ I'm worried about spending time migrating to capacitor just to turn around and migrate to Tauri when 2.0 is officially released. I already have a desktop FreeTubeTauri POC which I haven't really told anyone about because I didn't want to stretch myself thin between two forks of the same project. All in all, I have no idea when Tauri 2.0 will be officially released, so maybe, I should just take a weekend and migrate to capacitor for the time being. IDK🤷‍♀️. I've been thinking about it.

I was very sad when Tauri wouldn't launch on my Windows 10 Enterprise LTSC system, because the Edge WebView isn't included there, and I had some trouble installing it. Otherwise it's pretty nice and I used CinnyDesktop a lot. Now I run my own instance of it on the web, so even your PWA sounds interesting to me.

**Comment by MarmadileManteater** [comment]
I explored capacitor as a solution, and my takeaway was, after setting everything up, I found it would be just as easy to just create a blank Android Studio project with a webview in it.

Furthermore, some of the capacitor plugins this project would need do not fully work. For instance, the capacitor http plugin only handles full downloads of videos. It cannot handle video streaming. This is because capacitor overrides fetch with its own version which requires the entire response be loaded into memory before responding. 

### the future of FreeTubeCordova 

I have decided to just rewrite the JavaScript interface for android myself. Cordova is being gutted from the project, and it is being replaced with a proper android studio project. Some immediate benefits of this solution are *local api streaming* (#5). It *just works* out of the box now. I don't know what to say other than there is a setting that makes webviews behave like they do in electron (no need for CORS), but neither capacitor nor cordova seem to readily expose this. I assume this is because they rely on the webapp being served from `localhost` whereas you can only disable cors on `file` urls.

Another immediate benefit would be _Background Play_. In cordova, the way I was accomplishing background play was by pressing play on the video as soon as it paused in the background. This was hacky and had the effect of causing the video to stutter before going into the background. In this new version I am working on, I simply override the function that pauses the video in the background. Suddenly, background play is more consistent than ever.

I have found that being able to write my own kotlin rather than relying on plugins allows me to get more out of Android. For instance, the media controls plugin is fine, but it doesn't expose methods for changing the media notification progress and listening to seek events. When writing that code myself, I was easily able to just create a new media session, attach all the metadata and listen to those events.

![IMG_20240129_043536](https://github.com/MarmadileManteater/FreeTubeCordova/assets/106682128/2a1771b6-99a9-4c64-9092-1d65111c923c)

I just wanted to state what was happening with the project, and this seems like the issue for that. I realize I am not always on top of getting changes out there, so idk when this new version will be ready to release.

**Comment by MarmadileManteater** [comment]
If anyone is interested in trying out the new, cordova-less, and incomplete version I am working on, I got CI working: https://github.com/MarmadileManteater/FreeTubeCordova/actions/runs/7769115251 

This should just install over typical nightly, and if you updated to at least `nightly-385` before upgrading to this new build, it should keep all the application settings (`nightly-385` introduces storing the `db` files on the filesystem).

**Comment by ChunkyProgrammer** [comment]
Will close this issue as the app will be using webview instead
