### ISSUE TITLE
[Feature Request]: Self Hosting on Docker

### ISSUE THREAD

**Issue by BeatLink** [MarmadileManteater/FreeTubeCordova#129]
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

Freetube Cordova currently does not have a docker image available to install.

### Proposed Solution

Create a docker image for hosting FreeTube Cordova

### Alternatives Considered

None

### Issue Labels

ease of use improvement

**Comment by OwenTruong** [comment]
One thing to note is that my simple and small PR does not provide a way to sync across multiple devices. The data stays on the client/browser. The Nginx container only listens for the request to send the static site to the client. The benefit of running this kind of Docker image is that it can be run in the background, easy to change port, and easy to set up for others who are more familiar with Docker than JS technologies.


I think creating sync might be doable, but difficult. My idea is that an ExpressJS server (inside the container) will be needed to handle GET/POST request for the config data. However, this will require changes to how data is routed with IndexedDB for Docker-specific builds, and might be hard to maintain.

**Comment by BeatLink** [comment]
Dang. That's a shame regarding the sync implementation. If anyone has any ideas how it could be done id be keen to hear.

**Comment by OwenTruong** [comment]
My bad, I take back my word. It shouldn't be that hard to code assuming all of the data operations happen in _/src/datastores/handlers_ and _/src/store/modules_. We could have a docker.js as one of the handlers that helps sync data between server and Vue store / IndexedDB, but not too sure if this will work since I am not sure how state is managed in FreeTube. It seems like all of the store operations are abstracted in those two directories?

I would like to try implement the sync, but it will probably take a while as I am more familiar with React than Vue, and also need to read the source code more (especially in which file the Vue store interacts with the NeDB/IndexedDB).

**Comment by absidue** [comment]
The FreeTube PWA (like upstream) is a purely client side application, you can host it on any static file server, you can literally deploy it on GitHub Pages, so having a docker container for that seems slightly overkill.

**Comment by MarmadileManteater** [comment]
I'm leaving this issue closed automatically by the PR #153; there is now a [Dockerfile ](https://github.com/MarmadileManteater/FreeTubeCordova/blob/development/Dockerfile) which can be used to build a docker image if one is so inclined.

**Comment by FawkesOficial** [comment]
## anouncing
hey, as per https://github.com/MarmadileManteater/FreeTubeAndroid/blob/939634235b696193e7379af1bf62d8653f663ade/CONTRIBUTING.md?plain=1#L5


I would like to mention that I've been working on this very feature:
> One thing to note is that my simple and small PR does not provide a way to sync across multiple devices. The data stays on the client/browser. The Nginx container only listens for the request to send the static site to the client. The benefit of running this kind of Docker image is that it can be run in the background, easy to change port, and easy to set up for others who are more familiar with Docker than JS technologies.
> 
> I think creating sync might be doable, but difficult. My idea is that an ExpressJS server (inside the container) will be needed to handle GET/POST request for the config data. However, this will require changes to how data is routed with IndexedDB for Docker-specific builds, and might be hard to maintain.

## motivation

in fact, the reason that initially drove me the most to use this fork over the main repo was exactly the ability to self host freetube using docker so I could use it on my browser with multiple tabs open and also access it from my phone. 

> Dang. That's a shame regarding the sync implementation.

I agree.  although technically being able to self host it now, the PWA version still uses [localforage for storage](https://github.com/MarmadileManteater/FreeTubeAndroid/blob/42c08316af364167436b6d7259bcf624ab5a1522/src/datastores/handlers/web.js#L10) which makes it so that if we use different clients/browsers (desktop, phone, laptop, etc.), all data gets stored individually in each device.


this might? be the desired behavior for some people but I would assume that most would prefer sharing the same data between all their devices instead since self hosting this would be for personal/private use anyway.

## working

I have an initial implementation currently working on my fork:
https://github.com/FawkesOficial/FreeTubeAndroid/tree/selfhosted-data

I just took this:
> My idea is that an ExpressJS server (inside the container) will be needed to handle GET/POST request for the config data. However, this will require changes to how data is routed with IndexedDB for Docker-specific builds, and might be hard to maintain.

and also came across how #153 was implemented and thought we could do the exact same for the docker image.
intercept calls to localforage using a custom [_scripts/_localforage_docker.js](https://github.com/FawkesOficial/FreeTubeAndroid/blob/c325e723717be5dcd5943b5cb83c31ce617204a7/_scripts/_localforage_docker.js) and have a very simple and basic ExpressJS server reading and writing the db files.

## fixes

this would also address/fix? #459  since if self hosted, one can then access it through their phone's browser with PWA capabilities and essentially use it as an app\*, sharing the same data as they would on their desktop browser.
\*ex: in Chromium: go to the website -> click on three dots ( ⠇) -> Add to Home screen -> Install -> use it as any other android app

it would also allow users access to all db files by just mounting/mapping docker volumes to `/data` on the container (#358)

## implementation details

I would like to know if I should open a pr for this.
probably as a draft since I don't want to mess up the project's structure and I don't know if my exact approach is the best.
I just threw some things together until it worked the way I wanted it to/fit my needs ¯\\_(ツ)_\/¯

@MarmadileManteater sry for necrobumping, but I really think this deserves some attention :)
