### ISSUE TITLE
[Bug]: Live chat doesn't load

### ISSUE THREAD

**Issue by ChunkyProgrammer** [MarmadileManteater/FreeTubeCordova#151]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

1. go to a live video (ex: https://www.youtube.com/watch?v=jfKfPfyJRdk)
2. scroll to live chat
3. live chat loads forever
<img width="202" alt="live chat infinite loading" src="https://user-images.githubusercontent.com/78101139/232928177-9c376fa2-ef94-4855-ab5a-0af7d3fe5aab.png">

### Expected Behavior

Live chat should load or be hidden

### Issue Labels

API issue

### FreeTube Version

v0.18.0.107

### Operating System Version

Android 12

### Installation Method

.apk

### Primary API used

Local API

### Nightly Build

- [X] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by MarmadileManteater** [comment]
I realized that I forgot to change the check for `!IS_ELECTRON` to include cordova, but the reason the chat never loads is because the `isLoading` flag is never set to false when the `process.env.IS_ELECTRON` flag is `false`. It is supposed to show the text: "Live Chat is currently not supported in this build.", but since the `isLoading` flag never gets set to false, you can't see it. That might be a change worth making upstream because, while it doesn't involve the electron build, it would still probably effect the web version of freetube that can be tested with the `yarn dev:web` command upstream.

**Comment by MarmadileManteater** [comment]
I finally got around to pulling in upstream changes, and now, the PR that 🔨fixes this issue is merged into the `development` branch.
