### ISSUE TITLE
Location of config files?

### ISSUE THREAD

**Issue by cyberwolfie1** [MarmadileManteater/FreeTubeCordova#249]
**Important note**
Please check other open and closed issues for a similar question before posting a new one. 
-> I could not find a similar issue.

**Topic**
Please select what topic you are referring to.
- [ ] Coding
- [ ] Contribution
- [ ] Languages
- [ ] Setup
- [x] Other. Please specify:
Data location

**Question**
I am hoping to set up SyncThing to synchronize between FreeTube Cordova on my Android device and FreeTube on my laptop. On Linux, the history.db, playlists.db and profiles.db are by default located in ~/.config/FreeTube. I am unable to locate the same files on my Android device. 

Is it possible, and where would I find it?

**Comment by vdbhb59** [comment]
AFAIK, these should be located in the root data folder, /data/data or /data/apps. Not sure if this can be synchronised directly, but this is a valid question, as I am intrigued myself now.

**Comment by MarmadileManteater** [comment]
The cordova version of freetube is heavily based off the web version of freetube, and so, it currently does not write any `db` files to the file system unless you export them just like the web build. 

Persistent files for settings, history, playlists and subscriptions is a feature I want to implement #152 , but I haven't done it yet because it requires toying with nedb. For electron, nedb can just `fs.writeFile`. Since node built-ins are not available in cordova, there would need to be some sort of abstraction layer between nedb and cordova.

**Comment by cyberwolfie1** [comment]
Ok, I see. Consider this a +1 for #152 then :)
