### ISSUE TITLE
API Selection

### ISSUE THREAD

**Issue by IkelAtomig** [MarmadileManteater/FreeTubeCordova#408]
Why there is no way to use Local API similar to the Desktop App and only Invidious ?

I am using the Github Container Images.

**Comment by MarmadileManteater** [comment]
The PWA only supports invidious because it would take some work to add the local API, and it would involve adding some sort of server for the requests to proxy through. It is low on my priority list if I ever get to it.

It used to be that the Local API was an option, but that it wouldn't work. It would auto fallback to IV since local api was unimplemented. This was addressed by an upstream PR, so now, you can't even see the option for Local API because it wouldn't work if it was there.

**Comment by IkelAtomig** [comment]
>It used to be that the Local API was an option, but that it wouldn't work. It would auto fallback to IV since local api was unimplemented. This was addressed by an upstream PR, so now, you can't even see the option for Local API because it wouldn't work if it was there.

I am totally confused, Do you mean LocalAPI will not be shown in API selection as it is not implemented ?

**Comment by MarmadileManteater** [comment]
Sorry if I was unclear. The option used to be there even if it didn't work. Now, it is fixed so that it only shows if it can work.

**Comment by IkelAtomig** [comment]
Understood, 

> it would involve adding some sort of server for the requests to proxy through

Wouldn't it possible in the Docker images ?

Only problem would be android, If I am right.

**Comment by MarmadileManteater** [comment]
It is possible. It just requires work that I don't want to do right now.

The APK already supports local api in the same way the upstream electron app supports it. It just flips a switch in the webview to allow the requests to go through without a proxy.

**Comment by IkelAtomig** [comment]
Well, It could help me a lot, Cuz both Invidious and Piped are being blocked by YouTube (on my side). This could help if made available. I could just run this primarily instead of aforementioned both.
