### ISSUE TITLE
[Bug]: EXTREME battery drain.

### ISSUE THREAD

**Issue by derei** [MarmadileManteater/FreeTubeCordova#410]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

Unreasonably high battery drain. It effectively drained a fully charged samsung tablet in approx 4hrs. The tablet was also in a reduced power state (dimmed display, do not disturb, background apps closed, power saving mode).
The system reported 151% since last battery charge.

This is way beyond abnormal. Using other YouTube clients such as NewPipe, the power draw over similar periods of time and usage patterns is significantly less.

One possible explanation was found in this closed issue: https://github.com/FreeTubeApp/FreeTube/discussions/3248

But this doesn't excuse it. If Electron is not suitable for developing an efficient app, it should not be used, in my opinion. 

### Expected Behavior

I'd expect comparable power consumption to similar apps, under similar conditions. 

### Issue Labels

usability issue

### FreeTube Version

0.21.2.120 Beta

### Operating System Version

Android 13, OneUI5.1.1

### Installation Method

.apk

### Primary API used

Local API

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by MarmadileManteater** [comment]
There are likely a number of reasons Freetube Android uses more battery than NewPipe, some fixable, some unfixable.

1. (Unfixable) FreeTube Android is a webview app (**not electron based**, just a custom webview app) wheras NewPipe is a native app. Webview apps inherently do have more overhead but it shouldn't be too extreme, so I suggest another reason for a discrepancy in battery drain. 

2. (Fixable) I assume that NewPipe has some logic in it that turns off video streams in the backgroud. FreeTube Android does not, **currently**. It is a feature I want, but I haven't figured out how to make it seemless. Unless you specify "Audio only", it will always continuously stream video in the background. The webview itself **doesn't even have any idea its in the background**, and this is done _intentionally_ to prevent stuttering when entering the background. This likely leads to a higher than average battery drain in the background. Its something I would like to address, but I haven't at this point because switching formats with the current player causes the whole player to reload and the video often looses its place. To be clear, the current player is being replaced eventually, so when that happens, I'll revisit this.

**Comment by derei** [comment]
@MarmadileManteater  Thank you for the kind and detailed explanation.
This is rather unfortunate, because the features and functionality of FreeTube are uniquely practical. But due to the constraints you explained, and their effects over the software behaviour and functionality, I'll have to let this one go.

I believe it would be worth considering a full rebuild of FreeTube someday...
