### ISSUE TITLE
[Feature Request]: Allow disabling 60fps

### ISSUE THREAD

**Issue by glanduin** [MarmadileManteater/FreeTubeCordova#422]
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

On some low powered android phones, 60fps videos cause hiccups and slowdowns during playback. Right now the only way to disable 60fps is to adjust the video resolution to 480p which is unacceptable (visually). "Legacy formats" option unfortunately results in videos playing only in 360p so it is unusable. If there was a way to disable 60fps, playback of 720 or even 1080p videos (in dash formats) would be acceptable on low powered phones.

### Proposed Solution

Allow the disabling of 60fps under dash formats.

### Alternatives Considered

A repair of "legacy formats" so that the resolution can be increased over 360p.

### Issue Labels

improvement to existing feature

**Comment by absidue** [comment]
FreeTube uses the streams that are provided by YouTube, it can't magically force YouTube to create streams that they don't already provide. So the only thing that a disable 60fps options would be able to do is hide all 60fps streams from the quality selector which would leave you with 480p as the highest quality option.

That's also why it is impossible to "repair" the legacy formats, because YouTube doesn't provide the 720p legacy formats stream anymore, FreeTube can't use something that doesn't exist. The only reason YouTube still has the 360p one is because they have some edge cases in their official clients that still need it.

**Comment by glanduin** [comment]
There are Chromium extensions which can actually block 60fps videos, but i guess they do it directly from within the youtube website so it is a different kind of mechanism i assume. But if Freetube also uses Chromium as backend, maybe it could be possible.

**Comment by absidue** [comment]
Those extensions do exactly the same thing I was talking about, they just remove the 60fps options from the player but they can't create 30fps options that don't already exist.

**Comment by MarmadileManteater** [comment]
This is not possible.

**Comment by glanduin** [comment]
> Those extensions do exactly the same thing I was talking about, they just remove the 60fps options from the player but they can't create 30fps options that don't already exist.

most 60fps videos do have 30fps option with the same resolution if i m not mistaken.
