### ISSUE TITLE
[Feature Request]: Add supported links

### ISSUE THREAD

**Issue by ChunkyProgrammer** [MarmadileManteater/FreeTubeCordova#77]
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

Add supported links to APK file:

List of invidious instances (https://api.invidious.io)
List of piped instances (https://github.com/TeamPiped/Piped/wiki/Instances)
Cloudtube  (https://tube.cadence.moe/)
hooktube (hooktube.com) 

(It might be a good idea to automate getting the instances)

![Screenshots_2023-01-04-08-01-42](https://user-images.githubusercontent.com/78101139/210564275-52e9b91c-7d88-41f1-af49-dff6e14b9d2f.png)

### Proposed Solution

https://www.npmjs.com/package/cordova-universal-links-fix-plugin

### Alternatives Considered

None

### Issue Labels

ease of use improvement, new feature, support for external software

**Comment by ChunkyProgrammer** [comment]
Here's the github: https://github.com/felodt9090/cordova-universal-links-plugin#cordova-config-preferences

**Comment by MarmadileManteater** [comment]
I like the idea of supporting invidious links ~~, but I think that might cause issues with the 'Open in Invidious' links in FreeTube.I feel like there would have to be a setting for it which would control the visibility of the `Open in Invidious` links in FreeTube. _(but also, I'm not sure if the supported links can be modified after the app is installed)_~~ nvm, the `Open in YouTube` links work fine despite me adding those domains to universal links, so I was worried about a non-existent problem.

**Comment by MarmadileManteater** [comment]
> I like the idea of supporting invidious links ~~, but I think that might cause issues with the 'Open in Invidious' links in FreeTube.I feel like there would have to be a setting for it which would control the visibility of the `Open in Invidious` links in FreeTube. _(but also, I'm not sure if the supported links can be modified after the app is installed)_~~ nvm, the `Open in YouTube` links work fine despite me adding those domains to universal links, so I was worried about a non-existent problem.

_update:_ I was right the first time. I don't know why the `Open in YouTube` links were opening, but they aren't now. If something is a "supported link", it bypasses basically any attempt to open the site in a browser outside of using an in-app browser, and I found [this plugin which does provide that](https://www.npmjs.com/package/cordova-plugin-inappbrowser), but I'm on the fence if I want to use it to solve this problem. 

<img src="https://github.com/MarmadileManteater/FreeTubeCordova/assets/106682128/16c3ed71-9ae2-4c58-b50b-823e95db1f49"  width="200" />

Technically, you have to forcibly enable all of the domains you want to "Open by default" because there's no way for us to have these links verified by the `link` tag in the header (because we don't own these domains), so I don't actually know if it is a big deal that by enabling those links to open by default, you can't use the `Open in` links. This is similar to how, with the "Privacy Redirect" browser plugin, FreeTube on desktop opens a browser window that prompts you to open freetube.

**Comment by MarmadileManteater** [comment]
This feature should now be in the most recent release.
