### ISSUE TITLE
[Bug]:  white screen after app start

### ISSUE THREAD

**Issue by mondlicht-und-sterne** [MarmadileManteater/FreeTubeCordova#79]
app istall:  is okay
app start:  white screen after app start

my phone:
Samsung Galaxy S21 5G

my OS:
Android 13

![photo1673206603](https://user-images.githubusercontent.com/61406324/211215545-d72413c1-b757-46c1-a582-6a0633d428d9.jpeg)

**Comment by MarmadileManteater** [comment]
If this only happens sometimes, this is a 🏁race condition I personally am aware of, but I don't think it is documented anywhere. Sometimes, Cordova fails to load before the app loads, and then, the app will try to access Cordova methods and throw. If this happens all of the time and it has worked before, this could be related to #67; however, if this has never worked before and it always shows a white screen, this is probably a device / platform specific issue which will need to be 👁looked into.

**Comment by mondlicht-und-sterne** [comment]
Yes, the white screen always comes up for me.

**Comment by MarmadileManteater** [comment]
If you are comfortable with developer mode, you could connect your device to a computer with chrome installed and visit the `chrome://devices#inspect` page to view the inspect element for FreeTube in order to see what errors are displayed in the console. However, if you are not comfortable enough to do that, that it okay, but it would be helpful for me diagnosing the issue further.

**Comment by mondlicht-und-sterne** [comment]
Good news, I can launch the latest version 0.18.0.80. Thank you
![photo1673816053](https://user-images.githubusercontent.com/61406324/212566948-df8a05b4-b238-490d-afdc-e48a7c5144c0.jpeg)
